### ISSUE TITLE
When executing python3 streamdeck.py get the the error No module named 'tkinter'

### ISSUE THREAD

**Issue by ralphrabelo** [goglesquirmintontheiii/streamdeck-plus-software#3]
import tkinter
python3 streamdeck.py
Traceback (most recent call last):
  File "/home/***/streamdeck-plus-software/streamdeck.py", line 13, in <module>
    from PIL import Image, ImageDraw, ImageFont, ImageTk
  File "/home/***/.local/lib/python3.10/site-packages/PIL/ImageTk.py", line 29, in <module>
    import tkinter
ModuleNotFoundError: No module named 'tkinter'

**Comment by ralphrabelo** [comment]
Solved the problem with this:

For Ubuntu or other distros with Apt:
sudo apt-get install python3-tk

For Fedora:
sudo dnf install python3-tkinter

**Comment by goglesquirmintontheiii** [comment]
Glad to hear you fixed it, let me know if you need help with anything else ^
