### ISSUE TITLE
Error when running it in linux ubuntu

### ISSUE THREAD

**Issue by ralphrabelo** [goglesquirmintontheiii/streamdeck-plus-software#4]
python3 streamdeck.py
Checking for updates.. this won't take long! (You can press ctrl+C to cancel and you'll be able to disable auto-updates)
Seems you're new to the software!
Would you like to scan for an existing official Streamdeck software? This will let you import your icon and background packs. (y/n): y
Press enter when you've mounted your windows drive (so the program can reach it easily). This will scan /media/ for drives that have Windows on them.
Traceback (most recent call last):
  File "/home/***/streamdeck-plus-software/streamdeck.py", line 111, in <module>
    for subdir in os.listdir(user):
TypeError: listdir: path should be string, bytes, os.PathLike, integer or None, not list

**Comment by ralphrabelo** [comment]
Created the following directory inside the app's and it solved the problem
/media

**Comment by goglesquirmintontheiii** [comment]
Dunno why there was an issue with this, but I will look into it when I get a chance -- until then I'm gonna leave this issue open

**Comment by ralphrabelo** [comment]
the directory should exist inside the project

**Comment by goglesquirmintontheiii** [comment]
I'm 90% positive this won't happen anymore - but let me know if it does
